import { Hostel, Gym, SportsClub, Event, User, City } from './types';

export const CITIES: City[] = [
  { name: 'Jaipur', slug: 'jaipur', image: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=400', listings: 240 },
  { name: 'Delhi', slug: 'delhi', image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=400', listings: 580 },
  { name: 'Mumbai', slug: 'mumbai', image: 'https://images.unsplash.com/photo-1562979314-bee7453e911c?w=400', listings: 720 },
  { name: 'Bangalore', slug: 'bangalore', image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=400', listings: 650 },
  { name: 'Pune', slug: 'pune', image: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=400', listings: 380 },
  { name: 'Hyderabad', slug: 'hyderabad', image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400', listings: 420 },
];

export const HOSTELS: Hostel[] = [
  {
    id: '1',
    name: 'Coral Stay Hostel',
    city: 'Bangalore',
    address: 'Koramangala 5th Block, Bangalore',
    lat: 12.9279,
    lng: 77.6271,
    price_min: 4500,
    price_max: 7000,
    gender: 'mixed',
    amenities: ['WiFi', 'AC', 'Laundry', 'Meals', 'CCTV', 'Power Backup'],
    photos: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600', 'https://images.unsplash.com/photo-1529307474719-3d0a417aaf8a?w=600'],
    verified: true,
    rating: 4.7,
    reviews_count: 128,
    distance: 0.8,
    description: 'Modern hostel in the heart of Koramangala. Fully furnished rooms, 24/7 security, and a vibrant community of young professionals and students.',
    owner_name: 'Ravi Kumar',
    contact: '+91 98765 43210',
  },
  {
    id: '2',
    name: 'The Urban Nest PG',
    city: 'Bangalore',
    address: 'HSR Layout Sector 2, Bangalore',
    lat: 12.9116,
    lng: 77.6473,
    price_min: 6000,
    price_max: 9000,
    gender: 'girls',
    amenities: ['WiFi', 'AC', 'Gym', 'Meals', 'CCTV', 'Housekeeping', 'RO Water'],
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600'],
    verified: true,
    rating: 4.9,
    reviews_count: 94,
    distance: 1.2,
    description: 'Premium girls PG with all amenities. Safe, verified, and located in the prime HSR Layout.',
    owner_name: 'Priya Sharma',
    contact: '+91 87654 32109',
  },
  {
    id: '3',
    name: 'BhilloStay Boys Hostel',
    city: 'Pune',
    address: 'Viman Nagar, Pune',
    lat: 18.5679,
    lng: 73.9143,
    price_min: 3500,
    price_max: 5500,
    gender: 'boys',
    amenities: ['WiFi', 'Meals', 'CCTV', 'Sports Room', 'Laundry'],
    photos: ['https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600'],
    verified: false,
    rating: 4.3,
    reviews_count: 56,
    distance: 2.1,
    description: 'Affordable and comfortable boys hostel near Viman Nagar IT hub.',
    owner_name: 'Amit Patel',
    contact: '+91 76543 21098',
  },
  {
    id: '4',
    name: 'Skyline Students PG',
    city: 'Delhi',
    address: 'Lajpat Nagar, New Delhi',
    lat: 28.5672,
    lng: 77.2431,
    price_min: 7000,
    price_max: 12000,
    gender: 'mixed',
    amenities: ['WiFi', 'AC', 'Meals', 'Gym', 'Parking', 'CCTV', 'Power Backup', 'DTH TV'],
    photos: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600'],
    verified: true,
    rating: 4.6,
    reviews_count: 203,
    distance: 0.5,
    description: 'Premium PG in Lajpat Nagar with luxury amenities. Perfect for working professionals.',
    owner_name: 'Sunita Gupta',
    contact: '+91 65432 10987',
  },
  {
    id: '5',
    name: 'Jaipur Heritage Stay',
    city: 'Jaipur',
    address: 'Malviya Nagar, Jaipur',
    lat: 26.8483,
    lng: 75.8069,
    price_min: 3000,
    price_max: 5000,
    gender: 'boys',
    amenities: ['WiFi', 'Meals', 'CCTV', 'Laundry', 'Study Room'],
    photos: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600'],
    verified: true,
    rating: 4.4,
    reviews_count: 72,
    distance: 1.8,
    description: 'Heritage-style hostel in quiet Malviya Nagar area. Great for college students.',
    owner_name: 'Rajesh Meena',
    contact: '+91 54321 09876',
  },
  {
    id: '6',
    name: 'Bandra Tribe Co-Living',
    city: 'Mumbai',
    address: 'Bandra West, Mumbai',
    lat: 19.0596,
    lng: 72.8295,
    price_min: 15000,
    price_max: 25000,
    gender: 'mixed',
    amenities: ['WiFi', 'AC', 'Coworking Space', 'Gym', 'Rooftop', 'Housekeeping', 'Pool Table', 'Cafe'],
    photos: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600'],
    verified: true,
    rating: 4.8,
    reviews_count: 312,
    distance: 0.3,
    description: 'Premium co-living space in Bandra West. A community of like-minded young professionals.',
    owner_name: 'Nisha Shah',
    contact: '+91 43210 98765',
  },
];

export const GYMS: Gym[] = [
  {
    id: '1',
    name: 'Iron Paradise Gym',
    city: 'Bangalore',
    address: 'Indiranagar, Bangalore',
    lat: 12.9784,
    lng: 77.6408,
    price: 1200,
    type: 'gym',
    timing: '5:00 AM - 11:00 PM',
    photos: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600'],
    rating: 4.6,
    reviews_count: 89,
    distance: 0.6,
    description: 'State-of-the-art gym with modern equipment, personal trainers, and sauna.',
    amenities: ['Personal Trainer', 'Sauna', 'Locker Room', 'Parking'],
  },
  {
    id: '2',
    name: 'Zenflow Yoga Studio',
    city: 'Bangalore',
    address: 'Koramangala, Bangalore',
    lat: 12.9351,
    lng: 77.6245,
    price: 1500,
    type: 'yoga',
    timing: '6:00 AM - 9:00 PM',
    photos: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600'],
    rating: 4.9,
    reviews_count: 156,
    distance: 1.1,
    description: 'Premium yoga studio offering Hatha, Vinyasa, and meditation classes.',
    amenities: ['AC', 'Changing Room', 'Mats Provided', 'Cafe'],
  },
  {
    id: '3',
    name: 'CrossFit Tribe',
    city: 'Pune',
    address: 'Kharadi, Pune',
    lat: 18.5560,
    lng: 73.9444,
    price: 2500,
    type: 'crossfit',
    timing: '5:30 AM - 9:00 PM',
    photos: ['https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600'],
    rating: 4.7,
    reviews_count: 67,
    distance: 0.9,
    description: 'High-intensity CrossFit training with certified coaches.',
    amenities: ['Certified Coaches', 'Community Classes', 'Protein Bar'],
  },
  {
    id: '4',
    name: 'AquaFit Swimming Club',
    city: 'Mumbai',
    address: 'Andheri West, Mumbai',
    lat: 19.1337,
    lng: 72.8263,
    price: 3000,
    type: 'swimming',
    timing: '6:00 AM - 10:00 PM',
    photos: ['https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600'],
    rating: 4.5,
    reviews_count: 112,
    distance: 0.7,
    description: 'Olympic-size swimming pool with professional coaching for all levels.',
    amenities: ['Olympic Pool', 'Coaching', 'Changing Rooms', 'Café'],
  },
  {
    id: '5',
    name: 'FitHub Gym',
    city: 'Jaipur',
    address: 'C-Scheme, Jaipur',
    lat: 26.9124,
    lng: 75.7873,
    price: 800,
    type: 'gym',
    timing: '5:00 AM - 10:30 PM',
    photos: ['https://images.unsplash.com/photo-1521805492803-e4e6e3fb2813?w=600'],
    rating: 4.3,
    reviews_count: 45,
    distance: 1.5,
    description: 'Budget-friendly gym with all basic equipment and trainers.',
    amenities: ['Trainer', 'Locker', 'Water'],
  },
  {
    id: '6',
    name: 'Flex Fitness Studio',
    city: 'Delhi',
    address: 'Hauz Khas, New Delhi',
    lat: 28.5533,
    lng: 77.2006,
    price: 2000,
    type: 'mixed',
    timing: '6:00 AM - 10:00 PM',
    photos: ['https://images.unsplash.com/photo-1487176954706-8e0b80f0ffde?w=600'],
    rating: 4.8,
    reviews_count: 201,
    distance: 0.4,
    description: 'Premium multi-discipline fitness studio. Gym, Yoga, Zumba — all under one roof.',
    amenities: ['Sauna', 'Steam Room', 'Cafe', 'Parking', 'Personal Training'],
  },
];

export const SPORTS_CLUBS: SportsClub[] = [
  {
    id: '1',
    name: 'City FC — Football Club',
    city: 'Bangalore',
    address: 'Cubbon Park, Bangalore',
    lat: 12.9763,
    lng: 77.5929,
    sport: 'Football',
    skill_level: 'all',
    schedule: 'Weekends, 7:00 AM - 9:00 AM',
    members_count: 45,
    contact: '+91 98765 11111',
    description: 'Community football club open to all skill levels. We play every weekend!',
  },
  {
    id: '2',
    name: 'Smash Badminton League',
    city: 'Pune',
    address: 'Aundh Sports Complex, Pune',
    lat: 18.5590,
    lng: 73.8077,
    sport: 'Badminton',
    skill_level: 'intermediate',
    schedule: 'Mon, Wed, Fri — 6:00 PM - 9:00 PM',
    members_count: 28,
    contact: '+91 87654 22222',
    description: 'Competitive badminton league for intermediate players. Monthly tournaments.',
  },
  {
    id: '3',
    name: 'Jaipur Cricket Academy',
    city: 'Jaipur',
    address: 'SMS Stadium, Jaipur',
    lat: 26.9036,
    lng: 75.8117,
    sport: 'Cricket',
    skill_level: 'beginner',
    schedule: 'Daily, 5:30 AM - 8:00 AM',
    members_count: 60,
    contact: '+91 76543 33333',
    description: 'Learn cricket from scratch with professional coaches. Beginners welcome!',
  },
  {
    id: '4',
    name: 'Mumbai Ballers Basketball',
    city: 'Mumbai',
    address: 'Bandra Kurla Complex, Mumbai',
    lat: 19.0588,
    lng: 72.8681,
    sport: 'Basketball',
    skill_level: 'advanced',
    schedule: 'Tue, Thu, Sat — 7:00 PM - 9:00 PM',
    members_count: 20,
    contact: '+91 65432 44444',
    description: 'Competitive basketball for serious players. Join us for weekly scrimmages.',
  },
  {
    id: '5',
    name: 'Delhi Chess Circle',
    city: 'Delhi',
    address: 'Connaught Place, New Delhi',
    lat: 28.6305,
    lng: 77.2191,
    sport: 'Chess',
    skill_level: 'all',
    schedule: 'Every Sunday, 3:00 PM - 7:00 PM',
    members_count: 38,
    contact: '+91 54321 55555',
    description: 'Weekly chess meets for all levels. Tournaments every month.',
  },
  {
    id: '6',
    name: 'Hyderabad Runners Club',
    city: 'Hyderabad',
    address: 'KBR Park, Hyderabad',
    lat: 17.4239,
    lng: 78.4738,
    sport: 'Running',
    skill_level: 'all',
    schedule: 'Daily, 6:00 AM - 7:30 AM',
    members_count: 120,
    contact: '+91 43210 66666',
    description: 'The biggest running community in Hyderabad. Morning runs + weekend marathons.',
  },
];

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Bangalore Tech Meetup 2025',
    city: 'Bangalore',
    address: 'NIMHANS Convention Centre, Bangalore',
    lat: 12.9459,
    lng: 77.5948,
    date: '2025-04-15',
    time: '10:00 AM',
    category: 'tech',
    price: 0,
    is_free: true,
    photos: ['https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600'],
    rsvp_count: 342,
    organizer: 'TechBLR Community',
    description: 'Monthly tech meetup for developers, designers, and founders. Networking + talks.',
  },
  {
    id: '2',
    title: 'Open Mic Night — Koramangala',
    city: 'Bangalore',
    address: 'The Humming Tree, Koramangala',
    lat: 12.9347,
    lng: 77.6305,
    date: '2025-04-12',
    time: '7:00 PM',
    category: 'music',
    price: 200,
    is_free: false,
    photos: ['https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600'],
    rsvp_count: 89,
    organizer: 'Bangalore Open Mic',
    description: 'Open mic night for budding artists — music, comedy, poetry, spoken word.',
  },
  {
    id: '3',
    title: 'Jaipur Literary Festival — Youth Edition',
    city: 'Jaipur',
    address: 'Diggi Palace, Jaipur',
    lat: 26.9124,
    lng: 75.8077,
    date: '2025-04-20',
    time: '9:00 AM',
    category: 'culture',
    price: 500,
    is_free: false,
    photos: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600'],
    rsvp_count: 567,
    organizer: 'JLF Foundation',
    description: 'Youth edition of the world-famous Jaipur Literary Festival. Authors, books, debates.',
  },
  {
    id: '4',
    title: 'Mumbai Street Food Festival',
    city: 'Mumbai',
    address: 'Bandra Bandstand, Mumbai',
    lat: 19.0490,
    lng: 72.8200,
    date: '2025-04-18',
    time: '4:00 PM',
    category: 'food',
    price: 0,
    is_free: true,
    photos: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600'],
    rsvp_count: 1240,
    organizer: 'Mumbai Food Tribe',
    description: 'Annual street food festival with 50+ vendors from across Maharashtra.',
  },
  {
    id: '5',
    title: 'Comedy Night with Zakir Khan',
    city: 'Delhi',
    address: 'Siri Fort Auditorium, New Delhi',
    lat: 28.5491,
    lng: 77.2123,
    date: '2025-04-25',
    time: '8:00 PM',
    category: 'comedy',
    price: 999,
    is_free: false,
    photos: ['https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=600'],
    rsvp_count: 892,
    organizer: 'BookMyShow Live',
    description: 'Stand-up comedy night featuring Zakir Khan and special guests.',
  },
  {
    id: '6',
    title: 'Pune Startup Networking Night',
    city: 'Pune',
    address: 'WeWork Blue Ridge, Pune',
    lat: 18.5545,
    lng: 73.7966,
    date: '2025-04-14',
    time: '6:30 PM',
    category: 'networking',
    price: 0,
    is_free: true,
    photos: ['https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=600'],
    rsvp_count: 156,
    organizer: 'Pune Startup Club',
    description: 'Speed networking for founders, developers, and investors. Free drinks included!',
  },
];

export const COMMUNITY_USERS: User[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    email: 'arjun@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    city: 'Bangalore',
    college: 'IIT Bombay',
    company: 'Google',
    bio: 'SDE at Google. Love football, hiking, and street food. New to Bangalore!',
    hometown: 'Jaipur',
    interests: ['Football', 'Hiking', 'Coding', 'Street Food'],
    role: 'user',
  },
  {
    id: '2',
    name: 'Priya Nair',
    email: 'priya@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    city: 'Bangalore',
    college: 'NIT Trichy',
    company: 'Flipkart',
    bio: 'Product Manager at Flipkart. Into yoga, books, and indie music.',
    hometown: 'Kerala',
    interests: ['Yoga', 'Reading', 'Music', 'Cooking'],
    role: 'user',
  },
  {
    id: '3',
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    city: 'Pune',
    college: 'BITS Pilani',
    bio: 'Final year student at BITS. Cricket, photography, and startups.',
    hometown: 'Delhi',
    interests: ['Cricket', 'Photography', 'Entrepreneurship'],
    role: 'user',
  },
  {
    id: '4',
    name: 'Sneha Patil',
    email: 'sneha@example.com',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    city: 'Mumbai',
    company: 'Deloitte',
    bio: 'Consultant at Deloitte. Foodie, traveler, and dance lover.',
    hometown: 'Pune',
    interests: ['Dance', 'Travel', 'Food', 'Fitness'],
    role: 'user',
  },
  {
    id: '5',
    name: 'Kabir Singh',
    email: 'kabir@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    city: 'Delhi',
    college: 'Delhi University',
    bio: 'Law student at DU. Into debate, chess, and indie films.',
    hometown: 'Jaipur',
    interests: ['Chess', 'Debate', 'Films', 'Reading'],
    role: 'user',
  },
  {
    id: '6',
    name: 'Ananya Reddy',
    email: 'ananya@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
    city: 'Hyderabad',
    company: 'Microsoft',
    bio: 'Data scientist at Microsoft. Running, painting, and Carnatic music.',
    hometown: 'Chennai',
    interests: ['Running', 'Painting', 'Music', 'Data Science'],
    role: 'user',
  },
];
